topdir=../../../../

OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o  touch_wheel.o movie_rec.o
STUBS_AUTO_DEPS=boot.c capt_seq.c  touch_wheel.c movie_rec.c

include $(topdir)/platform/makefile_sub.inc
