void __attribute__((naked,noinline)) init_file_modules_task(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"                          //FFC138E8
                "BL      _Unmount_FileSystem\n" // + 
                "BL      sub_FFC0C45C\n"
                "SUBS    R4, R0, #0\n"
                "MOV     R0, #0x5000\n"
                "MOV     R1, #0\n"
                "ADD     R0, R0, #6\n"
                "BEQ     loc_FFC13908\n"
                "BL      sub_FFEA2270\n"   //PostLogicalEventToUI
"loc_FFC13908:\n"
                "BL      sub_FFC0C488_my\n"  //---------------->
                "MOV     R0, #0x5000\n"
                "CMP     R4, #0\n"
                "MOV     R1, R4\n"
                "ADD     R0, R0, #6\n"
                "LDMNEFD SP!, {R4,PC}\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFEA2270\n"   //PostLogicalEventToUI
 );
}

void __attribute__((naked,noinline)) sub_FFC0C488_my(){
 asm volatile(
                "STR     LR, [SP,#-4]!\n"
                "BL      Mount_FileSystem_my\n"   //-------------->
                "LDR     R3, =0x1DFC\n"
                "LDR     R2, [R3]\n"
                "CMP     R2, #0\n"
                "BNE     loc_FFC0C4C4\n"
                "BL      sub_FFC2E0F4\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFDF455C\n"
                "BL      sub_FFC2E0F4\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFE0513C\n"
                "BL      sub_FFC2E104\n"
                "AND     R0, R0, #0xFF\n"
                "BL      sub_FFDF4644\n"
"loc_FFC0C4C4:\n"
                "LDR     R2, =0x1DF8\n"
                "MOV     R3, #1\n"
                "STR     R3, [R2]\n"
                "LDR     PC, [SP],#4\n"
 );
}

void __attribute__((naked,noinline)) Mount_FileSystem_my(){         //code from FFE1CAF4
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R4, #0\n"
                "MOV     R5, R4\n"
                "LDR     R6, =0x65910\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE1C4D0\n"
                "LDR     R0, [R6,#0x38]\n"
                "BL      sub_FFE1BB64\n"
                "CMP     R0, R4\n"
                "MOV     R1, R5\n"
                "MOV     R0, R5\n"
                "BNE     loc_FFE1CB3C\n"
                "LDR     R3, =0xA43C\n"
                "LDR     R2, =0xA434\n"
                "STR     R1, [R3]\n"
                "LDR     R3, =0xA438\n"
                "STR     R1, [R2]\n"
                "STR     R1, [R3]\n"
"loc_FFE1CB3C:\n"
                "BL      sub_FFE1C520\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE1C850_my\n"  //----------------->
                "MOV     R4, R0\n"
                "MOV     R0, R5\n"
                "BL      sub_FFE1C8D8\n"
                "LDR     R1, [R6,#0x3C]\n"
                "AND     R2, R4, R0\n"
                "MOV     R0, R6\n"
                "BL      sub_FFE1CAA4\n"
                "STR     R0, [R6,#0x40]\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFE1C850_my(){
 asm volatile(
                "STMFD   SP!, {R4-R7,LR}\n"
                "LDR     R7, =0xA438\n"
                "LDR     R3, [R7]\n"
                "MOV     R4, R0\n"
                "CMP     R3, #0\n"
                "ADD     R3, R4, R4,LSL#1\n"
                "RSB     R3, R4, R3,LSL#3\n"
                "LDR     R6, =0x65948\n"
                "MOV     R5, R3,LSL#2\n"
                "MOV     R1, R4\n"
                "BNE     loc_FFE1C8C4\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFE1C5D8_my\n" //---------------->
                "SUBS    R3, R0, #0\n"
                "MOV     R1, R4\n"
                "BEQ     loc_FFE1C89C\n"
                "LDR     R0, [R6,R5]\n"
                "BL      sub_FFE1C72C\n"
                "MOV     R3, R0\n"
"loc_FFE1C89C:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R4\n"
                "BEQ     loc_FFE1C8B0\n"
                "BL      sub_FFE1BC3C\n"
                "MOV     R3, R0\n"
"loc_FFE1C8B0:\n"
                "CMP     R3, #0\n"
                "MOV     R0, R3\n"
                "MOVNE   R3, #1\n"
                "STRNE   R3, [R7]\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
"loc_FFE1C8C4:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R7,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFE1C5D8_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R5, R1\n"
                "MOV     R8, R5,LSL#1\n"
                "ADD     R3, R8, R5\n"
                "LDR     R2, =0x6594C\n"
                "SUB     SP, SP, #8\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "LDR     R1, [R2,R3,LSL#2]\n"
                "MOV     R6, #0\n"
                "STR     R6, [SP]\n"
                "MOV     R7, R0\n"
                "STR     R6, [SP,#4]\n"
                "CMP     R1, #6\n"
                "LDRLS   PC, [PC,R1,LSL#2]\n"
                "B       loc_FFE1C6D8\n"
                ".long loc_FFE1C67C\n"
                ".long loc_FFE1C630\n"
                ".long loc_FFE1C630\n"
                ".long loc_FFE1C630\n"
                ".long loc_FFE1C630\n"
                ".long loc_FFE1C6C8\n"
                ".long loc_FFE1C630\n"
"loc_FFE1C630:\n"
                "MOV     R0, #3\n"
                "MOV     R1, #0x200\n"
                "MOV     R2, #0\n"
                "BL      sub_FFC0DDB4\n" //AllocateExMem
                "SUBS    R6, R0, #0\n"
                "BEQ     loc_FFE1C710\n"
                "ADD     R12, R8, R5\n"
                "RSB     R12, R5, R12,LSL#3\n"
                "LDR     R4, =0x6595C\n"
                "MOV     R0, R7\n"
                "MOV     R1, #0\n"
                "MOV     R2, #1\n"
                "MOV     R3, R6\n"
                "MOV     LR, PC\n"
                "LDR     PC, [R4,R12,LSL#2]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFE1C684\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC0DE84\n"  // FreeExMem
"loc_FFE1C67C:\n"
                "MOV     R0, #0\n"
                "B       loc_FFE1C710\n"
"loc_FFE1C684:\n"
                "MOV     R0, R7\n"
                "BL      sub_FFE30078\n"
                "MOV     R1, R0\n"
                "ADD     R2, SP, #4\n"
                "MOV     R3, SP\n"
                "MOV     R0, R6\n"

                "STMFD   SP!, {R4-R11,LR}\n" // +
                "BL      mbr_read\n"    //-----------> 
                "LDMFD   SP!, {R4-R11,LR}\n" // +

         //     "BL      sub_FFE1BD68\n"      // original function
                "MOV     R4, R0\n"
                "MOV     R0, #3\n"
                "BL      sub_FFC0DE84\n"  // FreeExMem
                "CMP     R4, #0\n"
                "BNE     loc_FFE1C6E8\n"
                "MOV     R0, R7\n"
                "STR     R4, [SP,#4]\n"
                "BL      sub_FFE30078\n"
                "STR     R0, [SP]\n"
                "B       loc_FFE1C6E8\n"
"loc_FFE1C6C8:\n"
                "MOV     R3, #0\n"
                "MOV     R2, #0x40\n"
                "STMEA   SP, {R2,R3}\n"
                "B       loc_FFE1C6E8\n"
"loc_FFE1C6D8:\n"
                "MOV     R1, #0x358\n"
                "LDR     R0, =0xFFE1C3C0\n"
                "ADD     R1, R1, #2\n"
                "BL      sub_FFE8F444\n"   // DebugAssert
"loc_FFE1C6E8:\n"
                "LDR     R2, =0x65910\n"
                "ADD     R3, R8, R5\n"
                "LDMFD   SP, {R0,R12}\n"
                "RSB     R3, R5, R3,LSL#3\n"
                "MOV     R3, R3,LSL#2\n"
                "ADD     R1, R2, #0x48\n"
                "ADD     R2, R2, #0x44\n"
                "STR     R0, [R1,R3]\n"
                "STR     R12, [R2,R3]\n"
                "MOV     R0, #1\n"
"loc_FFE1C710:\n"
                "ADD     SP, SP, #8\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
}
