#include "lolevel.h"
#include "platform.h"
#include "core.h"
static long *nrflag = (long*)0x5b08; // ffd20124: (00005b08)
#include "../../../generic/capt_seq.c"
void __attribute__((naked,noinline)) capt_seq_task() { //EXPORT _sub_FFC5A2C_SsShootTask.c_13 ffc5fa2c
    asm volatile (
                 "STMFD   SP!, {R3-R9,LR}\n"
                 "LDR     R6, =0x2850\n"
                 "LDR     R4, =0x349a0\n"
                 "MOV     R9, #1\n"
                 "MOV     R7, #0\n"
"loc_ffc5fa40:\n"
                 "LDR     R0, [R6,#4]\n"
                 "MOV     R2, #0\n"
                 "MOV     R1, SP\n"
                 "BL      sub_ffc2936c\n"
                 "TST     R0, #1\n"
                 "BEQ     loc_ffc5fa6c\n"
                 "LDR     R1, =0x5b4\n"
                 "LDR     R0, =0xffc5f5e4\n" // "LDR     R0, =0x68537353\n"
                 "BL      sub_FFC0EB14\n"
                 "BL      sub_ffc0eacc\n"
                 "LDMFD   SP!, {R3-R9,PC}\n"
"loc_ffc5fa6c:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0]\n"
                 "CMP     R1, #0x1D\n"
                 "ADDLS   PC, PC, R1,LSL#2\n"
                 "B       loc_ffc5fcf4\n"
"loc_ffc5fa80:\n"
                 "B       loc_ffc5faf8\n"
"loc_ffc5fa84:\n"
                 "B       loc_ffc5fb5c\n"
"loc_ffc5fa88:\n"
                 "B       loc_ffc5fb98\n"
"loc_ffc5fa8c:\n"
                 "B       loc_ffc5fbac\n"
"loc_ffc5fa90:\n"
                 "B       loc_ffc5fba4\n"
"loc_ffc5fa94:\n"
                 "B       loc_ffc5fbb4\n"
"loc_ffc5fa98:\n"
                 "B       loc_ffc5fbbc\n"
"loc_ffc5fa9c:\n"
                 "B       loc_ffc5fbc4\n"
"loc_ffc5faa0:\n"
                 "B       loc_ffc5fc1c\n"
"loc_ffc5faa4:\n"
                 "B       loc_ffc5fc44\n"
"loc_ffc5faa8:\n"
                 "B       loc_ffc5fc28\n"
"loc_ffc5faac:\n"
                 "B       loc_ffc5fc34\n"
"loc_ffc5fab0:\n"
                 "B       loc_ffc5fc3c\n"
"loc_ffc5fab4:\n"
                 "B       loc_ffc5fc4c\n"
"loc_ffc5fab8:\n"
                 "B       loc_ffc5fc54\n"
"loc_ffc5fabc:\n"
                 "B       loc_ffc5fc5c\n"
"loc_ffc5fac0:\n"
                 "B       loc_ffc5fc64\n"
"loc_ffc5fac4:\n"
                 "B       loc_ffc5fc6c\n"
"loc_ffc5fac8:\n"
                 "B       loc_ffc5fc78\n"
"loc_ffc5facc:\n"
                 "B       loc_ffc5fc80\n"
"loc_ffc5fad0:\n"
                 "B       loc_ffc5fc88\n"
"loc_ffc5fad4:\n"
                 "B       loc_ffc5fc90\n"
"loc_ffc5fad8:\n"
                 "B       loc_ffc5fc98\n"
"loc_ffc5fadc:\n"
                 "B       loc_ffc5fca4\n"
"loc_ffc5fae0:\n"
                 "B       loc_ffc5fcac\n"
"loc_ffc5fae4:\n"
                 "B       loc_ffc5fcb4\n"
"loc_ffc5fae8:\n"
                 "B       loc_ffc5fcbc\n"
"loc_ffc5faec:\n"
                 "B       loc_ffc5fcc4\n"
"loc_ffc5faf0:\n"
                 "B       loc_ffc5fcd0\n"
"loc_ffc5faf4:\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5faf8:\n"
                 "BL      sub_ffc6033c\n"
                 "BL      shooting_expo_param_override\n" // added
                 "BL      sub_ffc5db3c\n"
// copied over from SX10/SX200
// added to avoid some incorrect behavior if overrides are used.
// it can cause some unexpected side effects. In this case, remove this code!
                 "MOV     R0, #0\n"
                 "STR     R0, [R4,#0x24]\n"  // fixes overrides  behavior at short shutter press
// end of added code
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BEQ     loc_ffc5fd00\n"
                 "BL      sub_ffc5f2c4\n"
                 "MOV     R5, R0\n"
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BEQ     loc_ffc5fb40\n"
                 "MOV     R0, #0xC\n"
                 "BL      sub_ffc64130\n"
                 "TST     R0, #1\n"
                 "STRNE   R9, [R6,#0x10]\n"
                 "LDRNE   R0, [R5,#8]\n"
                 "ORRNE   R0, R0, #0x40000000\n"
                 "STRNE   R0, [R5,#8]\n"
                 "BNE     loc_ffc5fd00\n"
"loc_ffc5fb40:\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffc5f568\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd203c4_my\n"       // ------------------> 
                 "BL      capt_seq_hook_raw_here\n"      // +
                 "TST     R0, #1\n"
                 "STRNE   R9, [R6,#0x10]\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fb5c:\n"
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_ffc5fb88\n"
                 "MOV     R0, #0xC\n"
                 "BL      sub_ffc64130\n"
                 "TST     R0, #1\n"
                 "LDRNE   R0, [SP]\n"
                 "MOVNE   R1, #1\n"
                 "LDRNE   R2, [R0,#0xC]\n"
                 "MOVNE   R0, #1\n"
                 "BNE     loc_ffc5fc14\n"
"loc_ffc5fb88:\n"
                 "LDR     R0, [SP]\n"
                 "BL      sub_ffc5fe18_my\n"       // ----------------->
"loc_ffc5fb90:\n"
                 "STR     R7, [R4,#0x24]\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fb98:\n"
                 "MOV     R0, #1\n"
                 "BL      sub_ffc605c4\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fba4:\n"
                 "BL      sub_ffc5ff90\n"
                 "B       loc_ffc5fb90\n"
"loc_ffc5fbac:\n"
                 "BL      sub_ffc6031c\n"
                 "B       loc_ffc5fb90\n"
"loc_ffc5fbb4:\n"
                 "BL      sub_ffc60324\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fbbc:\n"
                 "BL      sub_ffc604d4\n"
                 "B       loc_ffc5fc20\n"
"loc_ffc5fbc4:\n"
                 "LDR     R5, [R0,#0xC]\n"
                 "BL      sub_ffc6032c\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd1f3bc\n"
                 "TST     R0, #1\n"
                 "MOV     R8, R0\n"
                 "BNE     loc_ffc5fc04\n"
                 "BL      sub_ffc70d8c\n"
                 "STR     R0, [R5,#0x18]\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd202fc\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd206a0\n"
                 "MOV     R8, R0\n"
                 "LDR     R0, [R5,#0x18]\n"
                 "BL      sub_ffc70fc4\n"
"loc_ffc5fc04:\n"
                 "BL      sub_ffc6031c\n"
                 "MOV     R2, R5\n"
                 "MOV     R1, #9\n"
                 "MOV     R0, R8\n"
"loc_ffc5fc14:\n"
                 "BL      sub_ffc5dfb0\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc1c:\n"
                 "BL      sub_ffc6053c\n"
"loc_ffc5fc20:\n"
                 "BL      sub_ffc5db3c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc28:\n"
                 "LDR     R0, [R4,#0x54]\n"
                 "BL      sub_ffc6092c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc34:\n"
                 "BL      sub_ffc60be0\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc3c:\n"
                 "BL      sub_ffc60c74\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc44:\n"
                 "BL      sub_ffc6031c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc4c:\n"
                 "BL      sub_ffd1f5e8\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc54:\n"
                 "BL      sub_ffd1f7e0\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc5c:\n"
                 "BL      sub_ffd1f874\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc64:\n"
                 "BL      sub_ffd1f934\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc6c:\n"
                 "MOV     R0, #0\n"
"loc_ffc5fc70:\n"
                 "BL      sub_ffd1fb2c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc78:\n"
                 "BL      sub_ffd1fc7c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc80:\n"
                 "BL      sub_ffd1fd0c\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc88:\n"
                 "BL      sub_ffd1fdcc\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc90:\n"
                 "BL      sub_ffc60718\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fc98:\n"
                 "BL      sub_ffc607ac\n"
                 "BL      sub_ffc276bc\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fca4:\n"
                 "BL      sub_ffd1fa00\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcac:\n"
                 "BL      sub_ffd1fa44\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcb4:\n"
                 "BL      sub_ffc62900\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcbc:\n"
                 "BL      sub_ffc62980\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcc4:\n"
                 "BL      sub_ffc629dc\n"
                 "BL      sub_ffc629dc\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcd0:\n"
                 "LDRH    R0, [R4,#0x94]\n"
                 "CMP     R0, #4\n"
                 "LDRNEH  R0, [R4]\n" //"LDRHNE  R0, [R4]\n"
                 "SUBNE   R12, R0, #0x8200\n" // "SUBNE   IP, R0, 0x8200\n"
                 "SUBNES  R12, R12, #0x2A\n" // "SUBSNE  IP, IP, 0x2a\n"
                 "BNE     sub_ffc5fd00\n"
"loc_ffc5fce8:\n"
                 "BL      sub_ffc62980\n"
                 "BL      sub_ffc62da0\n"
                 "B       loc_ffc5fd00\n"
"loc_ffc5fcf4:\n"
                 "LDR     R1, =0x70b\n"
                 "LDR     R0, =0xffc5f5e4\n"
                 "BL      sub_FFC0EB14\n"
"loc_ffc5fd00:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0,#4]\n"
                 "LDR     R0, [R6]\n"
                 "BL      sub_ffc68c70\n"
                 "LDR     R5, [SP]\n"
                 "LDR     R0, [R5,#8]\n"
                 "CMP     R0, #0\n"
                 "LDREQ   R1, =0x132\n"
                 "LDREQ   R0, =0xffc5f5e4\n"
                 "BLEQ    sub_FFC0EB14\n"
                 "STR     R7, [R5,#8]\n"
                 "B       loc_ffc5fa40\n"
    );
}


void __attribute__((naked,noinline)) sub_ffd203c4_my() {
    asm volatile (
                 "STMFD   SP!, {R0-R8,LR}\n"
                 "MOV     R4, R0\n"
                 "BL      sub_ffd210d8\n"
                 "MVN     R1, #0x0\n" // "MOVL    R1, 0xFFFFFFFF\n"
                 "BL      sub_FFC68CA4\n"
                 "LDR     R5, =0x5B08\n"
                 "LDR     R0, [R5,#0xC]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_FFD20414\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, #0\n"
                 "BL      sub_FFC29BB4\n"
                 "STR     R0, [R5,#0xC]\n"
                 "MOV     R3, #0\n"
                 "STR     R3, [SP]\n"
                 "LDR     R3, =0xffd1febc\n"
                 "LDR     R0, =0xffd2062c\n" // "ADR     R0, 0xffd2062c\n"
                 "MOV     R2, #0x400\n"
                 "MOV     R1, #0x17\n"
                 "BL      sub_ffc29b80\n"
"loc_FFD20414:\n"
                 "MOV     R2, #4\n"
                 "ADD     R1, SP, #0x8\n"
                 "MOV     R0, #0x8A\n"
                 "BL      sub_ffc70bfc\n"
                 "TST     R0, #1\n"
                 "MOVNE   R1, #0x3B4\n"
                 "LDRNE   R0, =0xFFD20128\n" // "ADRNE   R0, 0xFFD20128\n"
                 "BLNE    sub_FFC0EB14\n"
                 "LDR     R6, =0x34A64\n"
                 "LDR     R7, =0x349A0\n"
                 "LDR     R3, [R6]\n"
                 "LDRSH   R2, [R6,#0xC]\n"
                 "LDRSH   R1, [R6,#0xE]\n"
                 "LDR     R0, [R7,#0x88]\n"
                 "BL      sub_FFCEF168\n"
                 "BL      sub_FFC49E68\n"
                 "LDR     R3, =0x5B10\n"
                 "STRH    R0, [R4,#0xA4]\n"
                 "SUB     R2, R3, #4\n"
                 "STRD    R2, [SP]\n"
                 "MOV     R1, R0\n"
                 "LDRH    R0, [R7,#0x5C]\n"
                 "LDRSH   R2, [R6,#0xC]\n"
                 "SUB     R3, R3, #8\n"
                 "BL      sub_FFD21744\n"
                 "BL      wait_until_remote_button_is_released\n"
                 "BL      capt_seq_hook_set_nr\n"                     // +
                 "B       sub_ffd20478\n"                             // continue function in firmware
    );
}

void __attribute__((naked,noinline)) sub_ffc5fe18_my() {
    asm volatile (
                 "STMFD   SP!, {R4-R6,LR}\n"
                 "LDR     R4, [R0,#0xC]\n"
                 "LDR     R6, =0x349A0\n"
                 "LDR     R0, [R4,#8]\n"
                 "MOV     R5, #0\n"
                 "ORR     R0, R0, #1\n"
                 "STR     R0, [R4,#8]\n"
                 "LDR     R0, [R6,#0x24]\n"
                 "CMP     R0, #0\n"
                 "MOVEQ   R0, #2\n"
                 "BLEQ    sub_FFC5C330\n"
                 "BL      sub_FFC6032C\n"
                 "LDR     R0, [R6,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_FFC5FEB4\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFC606CC\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFD1F028\n"
                 "CMP     R0, #0\n"
                 "MOV     R0, R4\n"
                 "BEQ     loc_FFC5FE8C\n"
                 "BL      sub_FFD1F0B4\n"
                 "TST     R0, #1\n"
                 "MOVNE   R2, R4\n"
                 "LDMNEFD SP!, {R4-R6,LR}\n"
                 "MOVNE   R1, #1\n"
                 "BNE     sub_FFC5DFB0\n"
                 "B       loc_FFC5FE90\n"
"loc_FFC5FE8C:\n"
                 "BL      sub_FFD1F078\n"
"loc_FFC5FE90:\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFC5F568\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFD202FC\n"
                 "BL      sub_FFD20F44\n"
                 "MOV     R0, R4\n"
                 "BL      sub_ffd203c4_my\n" // --------------->
                 "MOV     R5, R0\n"
                 "BL      capt_seq_hook_raw_here\n"      // +
                 "B       loc_FFC5FEC4\n"
"loc_FFC5FEB4:\n"
                 "LDR     R0, =0x2850\n"
                 "LDR     R0, [R0,#0x10]\n"
                 "CMP     R0, #0\n"
                 "MOVNE   R5, #0x1D\n"
"loc_FFC5FEC4:\n"
                 "BL      sub_FFC62980\n"
                 "BL      sub_FFC629C8\n"
                 "BL      sub_FFC62A08\n"
                 "MOV     R2, R4\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, R5\n"
                 "BL      sub_FFC5DFB0\n"
                 "BL      sub_FFD20654\n"
                 "CMP     R0, #0\n"
                 "LDRNE   R0, [R4,#8]\n"
                 "ORRNE   R0, R0, #0x2000\n"
                 "STRNE   R0, [R4,#8]\n"
                 "LDMFD   SP!, {R4-R6,PC}\n"
    );
}

