#include "lolevel.h"
#include "platform.h"
#include "core.h"
static long *nrflag = (long*)0x5b08; // ffd20124: (00005b08)

#include "../../../generic/capt_seq.c"
void __attribute__((naked,noinline)) capt_seq_task() { // ffc5f9DC
    asm volatile (
                 "STMFD   SP!, {R3-R9,LR}\n"
                 "LDR     R6, =0x2850\n"
                 "LDR     R4, =0x349a0\n"
                 "MOV     R9, #1\n"
                 "MOV     R7, #0\n"
"loc_ffc5f9f0:\n"
                 "LDR     R0, [R6,#4]\n"
                 "MOV     R2, #0\n"
                 "MOV     R1, SP\n"
                 "BL      sub_ffc2936c\n"
                 "TST     R0, #1\n"
                 "BEQ     loc_ffc5fa1c\n"
                 "LDR     R1, =0x5b4\n"
                 "LDR     R0, =0xffc5f594\n" // "LDR     R0, =0x68537353\n"
                 "BL      sub_FFC0EB14\n"    // debug assert
                 "BL      sub_ffc0eacc\n"    // eventproc_export_ExitTask
                 "LDMFD   SP!, {R3-R9,PC}\n"
"loc_ffc5fa1c:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0]\n"
                 "CMP     R1, #0x1D\n"
                 "ADDLS   PC, PC, R1,LSL#2\n"
                 "B       loc_ffc5fca4\n"
"loc_ffc5fa30:\n"
                 "B       loc_ffc5faa8\n"
"loc_ffc5fa34:\n"
                 "B       loc_ffc5fb0c\n"
"loc_ffc5fa38:\n"
                 "B       loc_ffc5fb48\n"
"loc_ffc5fa3c:\n"
                 "B       loc_ffc5fb5c\n"
"loc_ffc5fa40:\n"
                 "B       loc_ffc5fb54\n"
"loc_ffc5fa44:\n"
                 "B       loc_ffc5fb64\n"
"loc_ffc5fa48:\n"
                 "B       loc_ffc5fb6c\n"
"loc_ffc5fa4c:\n"
                 "B       loc_ffc5fb74\n"
"loc_ffc5fa50:\n"
                 "B       loc_ffc5fbcc\n"
"loc_ffc5fa54:\n"
                 "B       loc_ffc5fbf4\n"
"loc_ffc5fa58:\n"
                 "B       loc_ffc5fbd8\n"
"loc_ffc5fa5c:\n"
                 "B       loc_ffc5fbe4\n"
"loc_ffc5fa60:\n"
                 "B       loc_ffc5fbec\n"
"loc_ffc5fa64:\n"
                 "B       loc_ffc5fbfc\n"
"loc_ffc5fa68:\n"
                 "B       loc_ffc5fc04\n"
"loc_ffc5fa6c:\n"
                 "B       loc_ffc5fc0c\n"
"loc_ffc5fa70:\n"
                 "B       loc_ffc5fc14\n"
"loc_ffc5fa74:\n"
                 "B       loc_ffc5fc1c\n"
"loc_ffc5fa78:\n"
                 "B       loc_ffc5fc28\n"
"loc_ffc5fa7c:\n"
                 "B       loc_ffc5fc30\n"
"loc_ffc5fa80:\n"
                 "B       loc_ffc5fc38\n"
"loc_ffc5fa84:\n"
                 "B       loc_ffc5fc40\n"
"loc_ffc5fa88:\n"
                 "B       loc_ffc5fc48\n"
"loc_ffc5fa8c:\n"
                 "B       loc_ffc5fc54\n"
"loc_ffc5fa90:\n"
                 "B       loc_ffc5fc5c\n"
"loc_ffc5fa94:\n"
                 "B       loc_ffc5fc64\n"
"loc_ffc5fa98:\n"
                 "B       loc_ffc5fc6c\n"
"loc_ffc5fa9c:\n"
                 "B       loc_ffc5fc74\n"
"loc_ffc5faa0:\n"
                 "B       loc_ffc5fc80\n"
"loc_ffc5faa4:\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5faa8:\n"
                 "BL      sub_ffc602ec\n"
                 "BL      shooting_expo_param_override\n" // added
                 "BL      sub_ffc5daec\n"
// copied over from SX10/SX200
// added to avoid some incorrect behavior if overrides are used.
// it can cause some unexpected side effects. In this case, remove this code!
                 "MOV     R0, #0\n"
                 "STR     R0, [R4,#0x24]\n"  // fixes overrides  behavior at short shutter press
// end of added code
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BEQ     loc_ffc5fcb0\n"
                 "BL      sub_ffc5f274\n"
                 "MOV     R5, R0\n"
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BEQ     loc_ffc5faf0\n"
                 "MOV     R0, #0xC\n"
                 "BL      sub_ffc640e0\n"
                 "TST     R0, #1\n"
                 "STRNE   R9, [R6,#0x10]\n"
                 "LDRNE   R0, [R5,#8]\n"
                 "ORRNE   R0, R0, #0x40000000\n"
                 "STRNE   R0, [R5,#8]\n"
                 "BNE     loc_ffc5fcb0\n"
"loc_ffc5faf0:\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffc5f518\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd20314_my\n"       // ------------------> 
                 "BL      capt_seq_hook_raw_here\n"      // +
                 "TST     R0, #1\n"
                 "STRNE   R9, [R6,#0x10]\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fb0c:\n"
                 "LDR     R0, [R4,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_ffc5fb38\n"
                 "MOV     R0, #0xC\n"
                 "BL      sub_ffc640e0\n"
                 "TST     R0, #1\n"
                 "LDRNE   R0, [SP]\n"
                 "MOVNE   R1, #1\n"
                 "LDRNE   R2, [R0,#0xC]\n"
                 "MOVNE   R0, #1\n"
                 "BNE     loc_ffc5fbc4\n"
"loc_ffc5fb38:\n"
                 "LDR     R0, [SP]\n"
                 "BL      sub_ffc5fdc8_my\n"       // ----------------->
"loc_ffc5fb40:\n"
                 "STR     R7, [R4,#0x24]\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fb48:\n"
                 "MOV     R0, #1\n"
                 "BL      sub_ffc60574\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fb54:\n"
                 "BL      sub_ffc5ff40\n"
                 "B       loc_ffc5fb40\n"
"loc_ffc5fb5c:\n"
                 "BL      sub_ffc602cc\n"
                 "B       loc_ffc5fb40\n"
"loc_ffc5fb64:\n"
                 "BL      sub_ffc602d4\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fb6c:\n"
                 "BL      sub_ffc60484\n"
                 "B       loc_ffc5fbd0\n"
"loc_ffc5fb74:\n"
                 "LDR     R5, [R0,#0xC]\n"
                 "BL      sub_ffc602dc\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd1f30c\n"
                 "TST     R0, #1\n"
                 "MOV     R8, R0\n"
                 "BNE     loc_ffc5fbb4\n"
                 "BL      sub_ffc70d3c\n"
                 "STR     R0, [R5,#0x18]\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd2024c\n"
                 "MOV     R0, R5\n"
                 "BL      sub_ffd205f0\n"
                 "MOV     R8, R0\n"
                 "LDR     R0, [R5,#0x18]\n"
                 "BL      sub_ffc70f74\n"
"loc_ffc5fbb4:\n"
                 "BL      sub_ffc602cc\n"
                 "MOV     R2, R5\n"
                 "MOV     R1, #9\n"
                 "MOV     R0, R8\n"
"loc_ffc5fbc4:\n"
                 "BL      sub_ffc5df60\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbcc:\n"
                 "BL      sub_ffc604ec\n"
"loc_ffc5fbd0:\n"
                 "BL      sub_ffc5daec\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbd8:\n"
                 "LDR     R0, [R4,#0x54]\n"
                 "BL      sub_ffc608dc\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbe4:\n"
                 "BL      sub_ffc60b90\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbec:\n"
                 "BL      sub_ffc60c24\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbf4:\n"
                 "BL      sub_ffc602cc\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fbfc:\n"
                 "BL      sub_ffd1f538\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc04:\n"
                 "BL      sub_ffd1f730\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc0c:\n"
                 "BL      sub_ffd1f7c4\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc14:\n"
                 "BL      sub_ffd1f884\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc1c:\n"
                 "MOV     R0, #0\n"
"loc_ffc5fc20:\n"
                 "BL      sub_ffd1fa7c\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc28:\n"
                 "BL      sub_ffd1fbcc\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc30:\n"
                 "BL      sub_ffd1fc5c\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc38:\n"
                 "BL      sub_ffd1fd1c\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc40:\n"
                 "BL      sub_ffc606c8\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc48:\n"
                 "BL      sub_ffc6075c\n"
                 "BL      sub_ffc276bc\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc54:\n"
                 "BL      sub_ffd1f950\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc5c:\n"
                 "BL      sub_ffd1f994\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc64:\n"
                 "BL      sub_ffc628b0\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc6c:\n"
                 "BL      sub_ffc62930\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc74:\n"
                 "BL      sub_ffc6298c\n"
                 "BL      sub_ffc6294c\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fc80:\n"
                 "LDRH    R0, [R4,#0x94]\n"
                 "CMP     R0, #4\n"
                 "LDRNEH  R0, [R4]\n" //"LDRHNE  R0, [R4]\n"
                 "SUBNE   R12, R0, #0x8200\n" // "SUBNE   IP, R0, 0x8200\n"
                 "SUBNES  R12, R12, #0x2A\n" // "SUBSNE  IP, IP, 0x2a\n"
                 "BNE     sub_ffc5fd00\n"
                 "BL      sub_ffc62980\n"
                 "BL      sub_ffc62da0\n"
                 "B       loc_ffc5fcb0\n"
"loc_ffc5fca4:\n"
                 "LDR     R1, =0x70b\n"
                 "LDR     R0, =0xffc5f594\n"
                 "BL      sub_FFC0EB14\n"
"loc_ffc5fcb0:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0,#4]\n"
                 "LDR     R0, [R6]\n"
                 "BL      sub_ffc68c20\n"
                 "LDR     R5, [SP]\n"
                 "LDR     R0, [R5,#8]\n"
                 "CMP     R0, #0\n"
                 "LDREQ   R1, =0x132\n"
                 "LDREQ   R0, =0xffc5f594\n"
                 "BLEQ    sub_FFC0EB14\n"
                 "STR     R7, [R5,#8]\n"
                 "B       loc_ffc5f9f0\n"
    );
}


void __attribute__((naked,noinline)) sub_ffd20314_my() {
    asm volatile (
                 "STMFD   SP!, {R0-R8,LR}\n"
                 "MOV     R4, R0\n"
                 "BL      sub_ffd21028\n"
                 "MVN     R1, #0x0\n" // "MOVL    R1, 0xFFFFFFFF\n"
                 "BL      sub_FFC68C54\n"
                 "LDR     R5, =0x5B08\n"
                 "LDR     R0, [R5,#0xC]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_FFD20364\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, #0\n"
                 "BL      sub_FFC29BB4\n"
                 "STR     R0, [R5,#0xC]\n"
                 "MOV     R3, #0\n"
                 "STR     R3, [SP]\n"
                 "LDR     R3, =0xffd1fe0c\n"
                 "LDR     R0, =0xffd2057c\n" // "ADR     R0, 0xffd2062c\n"
                 "MOV     R2, #0x400\n"
                 "MOV     R1, #0x17\n"
                 "BL      sub_ffc29b80\n"
"loc_FFD20364:\n"
                 "MOV     R2, #4\n"
                 "ADD     R1, SP, #0x8\n"
                 "MOV     R0, #0x8A\n"
                 "BL      sub_ffc70bac\n"
                 "TST     R0, #1\n"
                 "MOVNE   R1, #0x3B4\n"
                 "LDRNE   R0, =0xFFD20078\n" // "ADRNE   R0, 0xFFD20128\n"
                 "BLNE    sub_FFC0EB14\n"
                 "LDR     R6, =0x34A64\n"
                 "LDR     R7, =0x349A0\n"
                 "LDR     R3, [R6]\n"
                 "LDRSH   R2, [R6,#0xC]\n"
                 "LDRSH   R1, [R6,#0xE]\n"
                 "LDR     R0, [R7,#0x88]\n"
                 "BL      sub_FFCEF118\n"
                 "BL      sub_FFC49E68\n"
                 "LDR     R3, =0x5B10\n"
                 "STRH    R0, [R4,#0xA4]\n"
                 "SUB     R2, R3, #4\n"
                 "STRD    R2, [SP]\n"
                 "MOV     R1, R0\n"
                 "LDRH    R0, [R7,#0x5C]\n"
                 "LDRSH   R2, [R6,#0xC]\n"
                 "SUB     R3, R3, #8\n"
                 "BL      sub_FFD21694\n"
                 "BL      wait_until_remote_button_is_released\n"
                 "BL      capt_seq_hook_set_nr\n"                     // +
                 "B       sub_ffd203c8\n"                             // continue function in firmware
    );
}

void __attribute__((naked,noinline)) sub_ffc5fdc8_my() {
    asm volatile (
                 "STMFD   SP!, {R4-R6,LR}\n"
                 "LDR     R4, [R0,#0xC]\n"
                 "LDR     R6, =0x349A0\n"
                 "LDR     R0, [R4,#8]\n"
                 "MOV     R5, #0\n"
                 "ORR     R0, R0, #1\n"
                 "STR     R0, [R4,#8]\n"
                 "LDR     R0, [R6,#0x24]\n"
                 "CMP     R0, #0\n"
                 "MOVEQ   R0, #2\n"
                 "BLEQ    sub_FFC5C2e0\n"
                 "BL      sub_FFC602dC\n"
                 "LDR     R0, [R6,#0x24]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_FFC5FE64\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFC6067C\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFD1EF78\n"
                 "CMP     R0, #0\n"
                 "MOV     R0, R4\n"
                 "BEQ     loc_FFC5FE3C\n"
                 "BL      sub_FFD1F004\n"
                 "TST     R0, #1\n"
                 "MOVNE   R2, R4\n"
                 "LDMNEFD SP!, {R4-R6,LR}\n"
                 "MOVNE   R1, #1\n"
                 "BNE     sub_FFC5DF60\n"
                 "B       loc_FFC5FE40\n"
"loc_FFC5FE3C:\n"
                 "BL      sub_FFD1EFC8\n"
"loc_FFC5FE40:\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFC5F518\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFD2024C\n"
                 "BL      sub_FFD20E94\n"
                 "MOV     R0, R4\n"
                 "BL      sub_ffd20314_my\n" // --------------->
                 "MOV     R5, R0\n"
                 "BL      capt_seq_hook_raw_here\n"      // +
                 "B       loc_FFC5FE74\n"
"loc_FFC5FE64:\n"
                 "LDR     R0, =0x2850\n"
                 "LDR     R0, [R0,#0x10]\n"
                 "CMP     R0, #0\n"
                 "MOVNE   R5, #0x1D\n"
"loc_FFC5FE74:\n"
                 "BL      sub_FFC62930\n"
                 "BL      sub_FFC62978\n"
                 "BL      sub_FFC629B8\n"
                 "MOV     R2, R4\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, R5\n"
                 "BL      sub_FFC5DF60\n"
                 "BL      sub_FFD205A4\n"
                 "CMP     R0, #0\n"
                 "LDRNE   R0, [R4,#8]\n"
                 "ORRNE   R0, R0, #0x2000\n"
                 "STRNE   R0, [R4,#8]\n"
                 "LDMFD   SP!, {R4-R6,PC}\n"
    );
}

