#include "lolevel.h"
#include "platform.h"
#include "core.h"
static long *nrflag = (long*)0x5b08; // ffd20124: (00005b08)

#include "../../../generic/capt_seq.c"
void __attribute__((naked,noinline)) capt_seq_task() { // ffc5fa40
    asm volatile (
"	STMFD	SP!, {R3-R9,LR} \n"                
"	LDR	R6, =0x2850 \n"                      
"	LDR	R4, =0x349A0 \n"                     
"	MOV	R9, #1 \n"                           
"	MOV	R7, #0 \n"                           
"loc_FFC5FA40:\n"
"	LDR	R0, [R6, #4] \n"                     
"	MOV	R2, #0 \n"                           
"	MOV	R1, SP \n"                           
"	BL	sub_FFC2936C \n"                      
"	TST	R0, #1 \n"                           
"	BEQ	loc_FFC5FA6C \n"                     
"	LDR	R1, =0x5B4 \n"                       
"	LDR	R0, =0xFFC5F5E4 \n"                  
"	BL	sub_FFC0EB14 \n"                      
"	BL	sub_FFC0EACC \n"                      
"	LDMFD	SP!, {R3-R9,PC} \n"                
"loc_FFC5FA6C:\n"
"	LDR	R0, [SP] \n"                         
"	LDR	R1, [R0] \n"                         
"	CMP	R1, #0x1D \n"                        
"	ADDLS	PC, PC, R1, LSL #2 \n"             
"	B	loc_FFC5FCF4 \n"                       
"	B	loc_FFC5FAF8 \n"                       
"	B	loc_FFC5FB5C \n"                       
"	B	loc_FFC5FB98 \n"                       
"	B	loc_FFC5FBAC \n"                       
"	B	loc_FFC5FBA4 \n"                       
"	B	loc_FFC5FBB4 \n"                       
"	B	loc_FFC5FBBC \n"                       
"	B	loc_FFC5FBC4 \n"                       
"	B	loc_FFC5FC1C \n"                       
"	B	loc_FFC5FC44 \n"                       
"	B	loc_FFC5FC28 \n"                       
"	B	loc_FFC5FC34 \n"                       
"	B	loc_FFC5FC3C \n"                       
"	B	loc_FFC5FC4C \n"                       
"	B	loc_FFC5FC54 \n"                       
"	B	loc_FFC5FC5C \n"                       
"	B	loc_FFC5FC64 \n"                       
"	B	loc_FFC5FC6C \n"                       
"	B	loc_FFC5FC78 \n"                       
"	B	loc_FFC5FC80 \n"                       
"	B	loc_FFC5FC88 \n"                       
"	B	loc_FFC5FC90 \n"                       
"	B	loc_FFC5FC98 \n"                       
"	B	loc_FFC5FCA4 \n"                       
"	B	loc_FFC5FCAC \n"                       
"	B	loc_FFC5FCB4 \n"                       
"	B	loc_FFC5FCBC \n"                       
"	B	loc_FFC5FCC4 \n"                       
"	B	loc_FFC5FCD0 \n"                       
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FAF8:\n"
"	BL	sub_FFC6033C \n" 
     "BL      shooting_expo_param_override\n" // added                    
"	BL	sub_FFC5DB3C \n"  
// copied over from SX10/SX200
// added to avoid some incorrect behavior if overrides are used.
// it can cause some unexpected side effects. In this case, remove this code!
                 "MOV     R0, #0\n"
                 "STR     R0, [R4,#0x24]\n"  // fixes overrides  behavior at short shutter press
// end of added code                   
"	LDR	R0, [R4, #0x24] \n"                  
"	CMP	R0, #0 \n"                           
"	BEQ	loc_FFC5FD00 \n"                     
"	BL	sub_FFC5F2C4 \n"                      
"	MOV	R5, R0 \n"                           
"	LDR	R0, [R4, #0x24] \n"                  
"	CMP	R0, #0 \n"                           
"	BEQ	loc_FFC5FB40 \n"                     
"	MOV	R0, #0xC \n"                         
"	BL	sub_FFC64130 \n"                      
"	TST	R0, #1 \n"                           
"	STRNE	R9, [R6, #0x10] \n"                
"	LDRNE	R0, [R5, #8] \n"                   
"	ORRNE	R0, R0, #0x40000000 \n"            
"	STRNE	R0, [R5, #8] \n"                   
"	BNE	loc_FFC5FD00 \n"                     
"loc_FFC5FB40:\n"
"	MOV	R0, R5 \n"                           
"	BL	sub_FFC5F568 \n"                      
"	MOV	R0, R5 \n"                           
"	BL	sub_ffd203c4_my \n"     // ------------------>
     "BL      capt_seq_hook_raw_here\n"      // +                
"	TST	R0, #1 \n"                           
"	STRNE	R9, [R6, #0x10] \n"                
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FB5C:\n"
"	LDR	R0, [R4, #0x24] \n"                  
"	CMP	R0, #0 \n"                           
"	BNE	loc_FFC5FB88 \n"                     
"	MOV	R0, #0xC \n"                         
"	BL	sub_FFC64130 \n"                      
"	TST	R0, #1 \n"                           
"	LDRNE	R0, [SP] \n"                       
"	MOVNE	R1, #1 \n"                         
"	LDRNE	R2, [R0, #0xC] \n"                 
"	MOVNE	R0, #1 \n"                         
"	BNE	loc_FFC5FC14 \n"                     
"loc_FFC5FB88:\n"
"	LDR	R0, [SP] \n"                         
"	BL	sub_ffc5fe18_my \n"     // ----------------->                 
"loc_FFC5FB90:\n"
"	STR	R7, [R4, #0x24] \n"                  
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FB98:\n"
"	MOV	R0, #1 \n"                           
"	BL	sub_FFC605C4 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FBA4:\n"
"	BL	sub_FFC5FF90 \n"                      
"	B	loc_FFC5FB90 \n"                       
"loc_FFC5FBAC:\n"
"	BL	sub_FFC6031C \n"                      
"	B	loc_FFC5FB90 \n"                       
"loc_FFC5FBB4:\n"
"	BL	sub_FFC60324 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FBBC:\n"
"	BL	sub_FFC604D4 \n"                      
"	B	loc_FFC5FC20 \n"                       
"loc_FFC5FBC4:\n"
"	LDR	R5, [R0, #0xC] \n"                   
"	BL	sub_FFC6032C \n"                      
"	MOV	R0, R5 \n"                           
"	BL	sub_FFD1F3BC \n"                      
"	TST	R0, #1 \n"                           
"	MOV	R8, R0 \n"                           
"	BNE	loc_FFC5FC04 \n"                     
"	BL	sub_FFC70D8C \n"                      
"	STR	R0, [R5, #0x18] \n"                  
"	MOV	R0, R5 \n"                           
"	BL	sub_FFD202FC \n"                      
"	MOV	R0, R5 \n"                           
"	BL	sub_FFD206A0 \n"                      
"	MOV	R8, R0 \n"                           
"	LDR	R0, [R5, #0x18] \n"                  
"	BL	sub_FFC70FC4 \n"                      
"loc_FFC5FC04:\n"
"	BL	sub_FFC6031C \n"                      
"	MOV	R2, R5 \n"                           
"	MOV	R1, #9 \n"                           
"	MOV	R0, R8 \n"                           
"loc_FFC5FC14:\n"
"	BL	sub_FFC5DFB0 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC1C:\n"
"	BL	sub_FFC6053C \n"                      
"loc_FFC5FC20:\n"
"	BL	sub_FFC5DB3C \n"                      
"	B	sub_FFC5FD00 \n"                       
"loc_FFC5FC28:\n"
"	LDR	R0, [R4, #0x54] \n"                  
"	BL	sub_FFC6092C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC34:\n"
"	BL	sub_FFC60BE0 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC3C:\n"
"	BL	sub_FFC60C74 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC44:\n"
"	BL	sub_FFC6031C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC4C:\n"
"	BL	sub_FFD1F5E8 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC54:\n"
"	BL	sub_FFD1F7E0 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC5C:\n"
"	BL	sub_FFD1F874 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC64:\n"
"	BL	sub_FFD1F934 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC6C:\n"
"	MOV	R0, #0 \n"                           
"	BL	sub_FFD1FB2C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC78:\n"
"	BL	sub_FFD1FC7C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC80:\n"
"	BL	sub_FFD1FD0C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC88:\n"
"	BL	sub_FFD1FDCC \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC90:\n"
"	BL	sub_FFC60718 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FC98:\n"
"	BL	sub_FFC607AC \n"                      
"	BL	sub_FFC276BC \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCA4:\n"
"	BL	sub_FFD1FA00 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCAC:\n"
"	BL	sub_FFD1FA44 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCB4:\n"
"	BL	sub_FFC62900 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCBC:\n"
"	BL	sub_FFC62980 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCC4:\n"
"	BL	sub_FFC629DC \n"                      
"	BL	sub_FFC6299C \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCD0:\n"
"	LDRH	R0, [R4, #0x94] \n"                 
"	CMP	R0, #4 \n"                           
"	LDRNEH	R0, [R4] \n"                      
"	SUBNE	R12, R0, #0x8200 \n"   // "SUBNE   IP, R0, 0x8200\n"            
"	SUBNES R12, R12, #0x2A \n"   // "SUBSNE  IP, IP, 0x2a\n"            
"	BNE	loc_FFC5FD00 \n"                     
"	BL	sub_FFC62980 \n"                      
"	BL	sub_FFC62DA0 \n"                      
"	B	loc_FFC5FD00 \n"                       
"loc_FFC5FCF4:\n"
"	LDR	R1, =0x70B \n"                       
"	LDR	R0, =0xFFC5F5E4 \n"                  
"	BL	sub_FFC0EB14 \n"                      
"loc_FFC5FD00:\n"
"	LDR	R0, [SP] \n"                         
"	LDR	R1, [R0, #4] \n"                     
"	LDR	R0, [R6] \n"                         
"	BL	sub_FFC68C70 \n"                      
"	LDR	R5, [SP] \n"                         
"	LDR	R0, [R5, #8] \n"                     
"	CMP	R0, #0 \n"                           
"	LDREQ	R1, =0x132 \n"                     
"	LDREQ	R0, =0xFFC5F5E4 \n"                
"	BLEQ	sub_FFC0EB14 \n"                    
"	STR	R7, [R5, #8] \n"                     
"	B	loc_FFC5FA40 \n"  
    );
}


void __attribute__((naked,noinline)) sub_ffd203c4_my() {
    asm volatile (
"	STMFD	SP!, {R0-R8,LR} \n"                
"	MOV	R4, R0 \n"                           
"	BL	sub_FFD210D8 \n"                      
"	MVN	R1, #0 \n"                           
"	BL	sub_FFC68CA4 \n"                      
"	LDR	R5, =0x5B08 \n"                      
"	LDR	R0, [R5, #0xC] \n"                   
"	CMP	R0, #0 \n"                           
"	BNE	loc_FFD20414 \n"                     
"	MOV	R1, #1 \n"                           
"	MOV	R0, #0 \n"                           
"	BL	sub_FFC29BB4 \n"                      
"	STR	R0, [R5, #0xC] \n"                   
"	MOV	R3, #0 \n"                           
"	STR	R3, [SP] \n"                         
"	LDR	R3, =0xFFD1FEBC \n"                  
"	LDR	R0, =0xFFD2062C \n"                  
"	MOV	R2, #0x400 \n"                       
"	MOV	R1, #0x17 \n"                        
"	BL	sub_FFC29B80 \n"                      
"loc_FFD20414:\n"
"	MOV	R2, #4 \n"                           
"	ADD	R1, SP, #8 \n"                       
"	MOV	R0, #0x8A \n"                        
"	BL	sub_FFC70BFC \n"                      
"	TST	R0, #1 \n"                           
"	MOVNE	R1, #0x3B4 \n"                     
"	LDRNE	R0, =0xFFD20128 \n"                
"	BLNE	sub_FFC0EB14 \n"                    
"	LDR	R6, =0x34A64 \n"                     
"	LDR	R7, =0x349A0 \n"                     
"	LDR	R3, [R6] \n"                         
"	LDRSH	R2, [R6, #0xC] \n"                 
"	LDRSH	R1, [R6, #0xE] \n"                 
"	LDR	R0, [R7, #0x88] \n"                  
"	BL	sub_FFCEF168 \n"                      
"	BL	sub_FFC49E68 \n"                      
"	LDR	R3, =0x5B10 \n"                      
"	STRH	R0, [R4, #0xA4] \n"                 
"	SUB	R2, R3, #4 \n"                       
     "STRD    R2, [SP]\n" 
"	MOV	R1, R0 \n"                           
"	LDRH	R0, [R7, #0x5C] \n"                 
"	LDRSH	R2, [R6, #0xC] \n"                 
"	SUB	R3, R3, #8 \n"                       
"	BL	sub_FFD21744 \n" 
     "BL      wait_until_remote_button_is_released\n"
     "BL      capt_seq_hook_set_nr\n"  
     "B       sub_ffd20478\n"                           // continue function in firmware
    );
}

void __attribute__((naked,noinline)) sub_ffc5fe18_my() {
    asm volatile (
"	STMFD	SP!, {R4-R6,LR} \n"                
"	LDR	R4, [R0, #0xC] \n"                   
"	LDR	R6, =0x349A0 \n"                     
"	LDR	R0, [R4, #8] \n"                     
"	MOV	R5, #0 \n"                           
"	ORR	R0, R0, #1 \n"                       
"	STR	R0, [R4, #8] \n"                     
"	LDR	R0, [R6, #0x24] \n"                  
"	CMP	R0, #0 \n"                           
"	MOVEQ	R0, #2 \n"                         
"	BLEQ	sub_FFC5C330 \n"                    
"	BL	sub_FFC6032C \n"                      
"	LDR	R0, [R6, #0x24] \n"                  
"	CMP	R0, #0 \n"                           
"	BNE	loc_FFC5FEB4 \n"                     
"	MOV	R0, R4 \n"                           
"	BL	sub_FFC606CC \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD1F028 \n"                      
"	CMP	R0, #0 \n"                           
"	MOV	R0, R4 \n"                           
"	BEQ	loc_FFC5FE8C \n"                     
"	BL	sub_FFD1F0B4 \n"                      
"	TST	R0, #1 \n"                           
"	MOVNE	R2, R4 \n"                         
"	LDMNEFD	SP!, {R4-R6,LR} \n"              
"	MOVNE	R1, #1 \n"                         
"	BNE	sub_FFC5DFB0 \n"                     
"	B	loc_FFC5FE90 \n"                       
"loc_FFC5FE8C:\n"
"	BL	sub_FFD1F078 \n"                      
"loc_FFC5FE90:\n"
"	MOV	R0, R4 \n"                           
"	BL	sub_FFC5F568 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD202FC \n"                      
"	BL	sub_FFD20F44 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_ffd203c4_my \n"  // --------------->                    
"	MOV	R5, R0 \n"  
"BL      capt_seq_hook_raw_here\n"      // +                       
"	B	loc_FFC5FEC4 \n"                       
"loc_FFC5FEB4:\n"
"	LDR	R0, =0x2850 \n"                      
"	LDR	R0, [R0, #0x10] \n"                  
"	CMP	R0, #0 \n"                           
"	MOVNE	R5, #0x1D \n"                      
"loc_FFC5FEC4:\n"
"	BL	sub_FFC62980 \n"                      
"	BL	sub_FFC629C8 \n"                      
"	BL	sub_FFC62A08 \n"                      
"	MOV	R2, R4 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, R5 \n"                           
"	BL	sub_FFC5DFB0 \n"                      
"	BL	sub_FFD20654 \n"                      
"	CMP	R0, #0 \n"                           
"	LDRNE	R0, [R4, #8] \n"                   
"	ORRNE	R0, R0, #0x2000 \n"                
"	STRNE	R0, [R4, #8] \n"                   
"	LDMFD	SP!, {R4-R6,PC} \n" 
    );
}

