;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: B3-432E-F558-21			    |
; |				Ilfak Guilfanov				    |
; +-------------------------------------------------------------------------+
;



; =============== S U B	R O U T	I N E =======================================


sub_FF080EFC				; DATA XREF: sub_FF0813C0+8o
					; ROM:off_FF081894o

var_68		= -0x68
var_60		= -0x60
var_5C		= -0x5C
var_4C		= -0x4C
var_38		= -0x38
var_34		= -0x34
var_30		= -0x30
var_2C		= -0x2C
var_28		= -0x28
var_24		= -0x24
var_20		= -0x20
var_1C		= -0x1C

		STMFD	SP!, {R4-R8,LR}
		SUB	SP, SP,	#0x50
		MOV	R8, #0
		LDR	R5, =0x38B0
		STR	R8, [SP,#0x68+var_28]
		STR	R8, [SP,#0x68+var_30]
		STR	R8, [R5,#0xC4]
		LDR	R1, [R5,#0x44]
		MOV	R4, R0
		CMP	R1, #3
		MOV	R6, R8
		MOV	R7, #1
		BNE	loc_FF080F54
		LDR	R0, [R5,#0x148]
		LDR	R1, [R5,#0x14C]
		CMP	R0, R1
		BNE	loc_FF0810E0
		MOV	R0, #4
		STR	R0, [R5,#0x44]
		MOV	R0, 0xFFFFFFFF
		STR	R0, [R5,#0x148]
		B	loc_FF080F5C
; ---------------------------------------------------------------------------

loc_FF080F54				; CODE XREF: sub_FF080EFC+30j
		CMP	R1, #4
		BNE	loc_FF0810E0

loc_FF080F5C				; CODE XREF: sub_FF080EFC+54j
		LDRH	R0, [R5,#6]
		CMP	R0, #3
		BNE	loc_FF080F94
		LDR	R0, [R5,#0xC8]
		CMP	R0, #0
		LDREQ	R1, =0x86B
		LDREQ	R0, =aMovierecorder_ ; "MovieRecorder.c"
		BLEQ	0x68B104
		LDR	R0, [R5,#0x6C]
		LDR	R1, [R5,#0xC8]
		BL	0x69092C
		CMP	R1, #0
		MOVNE	R7, #0
		BNE	loc_FF080FB0

loc_FF080F94				; CODE XREF: sub_FF080EFC+68j
		ADD	R3, SP,	#0x68+var_30
		ADD	R2, SP,	#0x68+var_2C
		ADD	R1, SP,	#0x68+var_28
		ADD	R0, SP,	#0x68+var_24
		BL	sub_FF1EEDDC
		MOVS	R8, R0
		BNE	loc_FF080FCC

loc_FF080FB0				; CODE XREF: sub_FF080EFC+94j
		LDR	R0, [R5,#0x34]
		CMP	R0, #1
		BNE	loc_FF0810E8
		LDR	R0, [R5,#0x6C]
		LDR	R1, [R5,#0x48]
		CMP	R0, R1
		BCC	loc_FF0810E8

loc_FF080FCC				; CODE XREF: sub_FF080EFC+B0j
		MOV	R0, R8
		BL	sub_FF07EEF4
		BL	sub_FF08202C
		LDR	R2, [R5,#0x64]
		ADD	R3, SP,	#0x68+var_20
		MOV	R1, 0xFFFFFFFE
		MOV	R0, #0
		ADD	R7, SP,	#0x68+var_4C
		STMIA	R7, {R0-R3}
		LDR	R3, [R4,#0x1C]
		LDR	R1, [R5,#0x74]
		LDR	R2, [R5,#0x78]
		ADD	R0, SP,	#0x68+var_1C
		ADD	R4, SP,	#0x68+var_5C
		STMIA	R4, {R0-R3}
		MOV	R3, #0
		MOV	R1, #0x40
		STMEA	SP, {R1,R3}
		MOV	R2, #0
		STR	R3, [SP,#0x68+var_60]
		LDR	R3, =0x43A1C
		MOV	R1, R2
		MOV	R0, R2
		BL	sub_FF192968
; ---------------------------------------------------------------------------
		LDR	R0, [R5,#0x1C]
		LDR	R1, [R5,#0x60]
		BL	0x68AA1C
		CMP	R0, #9
		BNE	loc_FF0810B4

loc_FF081040				; CODE XREF: sub_FF080EFC+278j
		MOV	R1, #1
		B	loc_FF081208
; ---------------------------------------------------------------------------
off_FF081048	DCD sub_FF080038	; DATA XREF: ROM:loc_FF080168r
dword_FF08104C	DCD 0xDA8		; DATA XREF: sub_FF080178+78r
dword_FF081050	DCD 0xE3D		; DATA XREF: ROM:FF080430r
dword_FF081054	DCD 0xFF07EED0		; DATA XREF: sub_FF080460:loc_FF0806BCr
					; sub_FF080B4C+364r
dword_FF081058	DCD 0x4397C		; DATA XREF: sub_FF080460+26Cr
					; sub_FF080460+354r ...
dword_FF08105C	DCD 0x3928		; DATA XREF: sub_FF080460+304r
					; sub_FF080818+290r ...
dword_FF081060	DCD 0x43A1C		; DATA XREF: sub_FF080818+D8r
					; sub_FF080EFC+120r ...
dword_FF081064	DCD 0xC25		; DATA XREF: sub_FF080B18+10r
off_FF081068	DCD aMovierecorder_	; DATA XREF: sub_FF080B18+24r
					; sub_FF080B4C+C8r ...
					; "MovieRecorder.c"
dword_FF08106C	DCD 0xFFF00		; DATA XREF: sub_FF080B4C+28r
dword_FF081070	DCD 0x74C		; DATA XREF: sub_FF080B4C:loc_FF080C10r
dword_FF081074	DCD 0x38B2		; DATA XREF: sub_FF080B4C:loc_FF080C34r
dword_FF081078	DCD 0x38B4		; DATA XREF: sub_FF080B4C+FCr
dword_FF08107C	DCD 0x3900		; DATA XREF: sub_FF080B4C+110r
dword_FF081080	DCD 0x3904		; DATA XREF: sub_FF080B4C+124r
dword_FF081084	DCD 0x3A10		; DATA XREF: sub_FF080B4C+140r
					; sub_FF080B4C+154r
unk_FF081088	DCB 0x60 ; `		; DATA XREF: sub_FF080B4C+170r
		DCB  0xA
		DCB 0x28 ; (
		DCB 0x4A ; J
dword_FF08108C	DCD 0x484B4600		; DATA XREF: sub_FF080B4C+17Cr
dword_FF081090	DCD 0x3870600		; DATA XREF: sub_FF080B4C+180r
dword_FF081094	DCD 0x39D8		; DATA XREF: sub_FF080B4C+25Cr
dword_FF081098	DCD 0x20F000		; DATA XREF: sub_FF080B4C+270r
off_FF08109C	DCD sub_FF080B18	; DATA XREF: sub_FF080B4C+29Cr
off_FF0810A0	DCD sub_FF080818	; DATA XREF: sub_FF080B4C+2ECr
off_FF0810A4	DCD sub_FF080460	; DATA XREF: sub_FF080B4C+2FCr
off_FF0810A8	DCD unk_FF49F090	; DATA XREF: sub_FF080B4C+308r
off_FF0810AC	DCD loc_FF080454	; DATA XREF: sub_FF080B4C+328r
					; sub_FF081BE0+DCr ...
dword_FF0810B0	DCD 0x86B		; DATA XREF: sub_FF080EFC+74r
; ---------------------------------------------------------------------------

loc_FF0810B4				; CODE XREF: sub_FF080EFC+140j
		LDR	R0, [SP,#0x68+var_20]
		CMP	R0, #0
		BEQ	loc_FF0810C8

loc_FF0810C0				; CODE XREF: sub_FF080EFC+284j
		MOV	R1, #1
		B	loc_FF081220
; ---------------------------------------------------------------------------

loc_FF0810C8				; CODE XREF: sub_FF080EFC+1C0j
		MOV	R0, #1
		BL	sub_FF192A14
		BL	sub_FF192AC0
; ---------------------------------------------------------------------------
		MOV	R0, #5
		STR	R6, [R5,#0x34]!
		STR	R0, [R5,#0x10]

loc_FF0810E0				; CODE XREF: sub_FF080EFC+40j
					; sub_FF080EFC+5Cj ...
		ADD	SP, SP,	#0x50
		LDMFD	SP!, {R4-R8,PC}
; ---------------------------------------------------------------------------

loc_FF0810E8				; CODE XREF: sub_FF080EFC+BCj
					; sub_FF080EFC+CCj
		CMP	R7, #1
		BNE	loc_FF081334
		MOV	R0, #1
		STR	R0, [R5,#0x38]
		LDR	R0, [R5,#0x6C]
		LDR	R7, [R4,#0xC]
		CMP	R0, #0
		LDRNE	R8, [SP,#0x68+var_28]
		LDRNE	R12, [SP,#0x68+var_24]
		BNE	loc_FF0811A0
		LDR	R0, [R4,#0x20]
		LDR	R2, [R5,#0x64]
		ADD	R3, SP,	#0x68+var_20
		MOV	R1, 0xFFFFFFFF
		ADD	R8, SP,	#0x68+var_4C
		STMIA	R8, {R0-R3}
		LDR	R3, [R4,#0x1C]
		LDR	R1, [R5,#0x74]
		LDR	R2, [R5,#0x78]
		ADD	R0, SP,	#0x68+var_1C
		ADD	R8, SP,	#0x68+var_5C
		STMIA	R8, {R0-R3}
		LDR	R1, [SP,#0x68+var_2C]
		LDR	R2, [SP,#0x68+var_28]
		LDR	R3, [SP,#0x68+var_30]
		STMFA	SP, {R1,R3}
		STR	R2, [SP,#0x68+var_68]
		LDMIB	R4, {R0,R1}
		LDR	R3, [SP,#0x68+var_24]
		MOV	R2, R7
		BL	sub_FF192968
; ---------------------------------------------------------------------------
		LDR	R0, [R5,#0x1C]
		LDR	R1, [R5,#0x60]
		BL	0x68AA1C
		CMP	R0, #9
		BEQ	loc_FF081040
		LDR	R0, [SP,#0x68+var_20]
		CMP	R0, #0
		BNE	loc_FF0810C0
		MOV	R0, #1
		BL	sub_FF192A14
		LDR	R0, [SP,#0x68+var_1C]
		LDR	R1, [SP,#0x68+var_24]
		ADD	R12, R1, R0
		LDR	R1, [SP,#0x68+var_28]
		SUB	R8, R1,	R0

loc_FF0811A0				; CODE XREF: sub_FF080EFC+210j
		LDR	R0, [R4,#0x20]
		LDR	R1, [R5,#0x68]
		LDR	R2, [R5,#0x64]
		ADD	R3, SP,	#0x68+var_20
		ADD	LR, SP,	#0x68+var_4C
		STMIA	LR, {R0-R3}
		LDR	R3, [R4,#0x1C]
		LDR	R1, [R5,#0x74]
		LDR	R2, [R5,#0x78]
		ADD	R0, SP,	#0x68+var_1C
		ADD	LR, SP,	#0x68+var_5C
		STMIA	LR, {R0-R3}
		LDR	R2, [SP,#0x68+var_2C]
		LDR	R3, [SP,#0x68+var_30]
		STMFA	SP, {R2,R3}
		STR	R8, [SP,#0x68+var_68]
		LDMIB	R4, {R0,R1}
		MOV	R3, R12
		MOV	R2, R7
		BL	sub_FF192968
; ---------------------------------------------------------------------------
		LDR	R0, [R5,#0x1C]
		LDR	R1, [R5,#0x60]
		BL	0x68AA1C
		CMP	R0, #9
		BNE	loc_FF081210
		MOV	R1, #0

loc_FF081208				; CODE XREF: sub_FF080EFC+148j
		MOV	R0, #0x90000
		B	loc_FF081224
; ---------------------------------------------------------------------------

loc_FF081210				; CODE XREF: sub_FF080EFC+304j
		LDR	R0, [SP,#0x68+var_20]
		CMP	R0, #0
		BEQ	loc_FF08122C
		MOV	R1, #0

loc_FF081220				; CODE XREF: sub_FF080EFC+1C8j
		MOV	R0, #0xA0000

loc_FF081224				; CODE XREF: sub_FF080EFC+310j
		BL	sub_FF07EE44
		B	loc_FF0810E0
; ---------------------------------------------------------------------------

loc_FF08122C				; CODE XREF: sub_FF080EFC+31Cj
		MOV	R0, #0
		BL	sub_FF192A14
		LDR	R0, [R5,#0x144]
		CMP	R0, #1
		BNE	loc_FF0812BC
		LDR	R0, [R5,#0x68]
		LDR	R1, [R5,#0x64]
		BL	0x69092C
		MOVS	R4, R1
		STREQ	R6, [R5,#0x144]
		BEQ	loc_FF0812BC
		LDR	R7, [SP,#0x68+var_24]
		MOV	R2, #4
		ADD	R1, R7,	#4
		ADD	R0, SP,	#0x68+var_34
		BL	0x690174
		LDR	R0, [SP,#0x68+var_34]
		MOV	R1, R0,LSR#24
		AND	R2, R0,	#0xFF0000
		ORR	R1, R1,	R2,LSR#8
		AND	R2, R0,	#0xFF00
		ORR	R1, R1,	R2,LSL#8
		ORR	R0, R1,	R0,LSL#24
		BIC	R0, R0,	#0x1E000
		ORR	R0, R0,	R4,LSL#13
		MOV	R1, R0,LSR#24
		AND	R2, R0,	#0xFF0000
		ORR	R1, R1,	R2,LSR#8
		AND	R2, R0,	#0xFF00
		ORR	R1, R1,	R2,LSL#8
		ORR	R0, R1,	R0,LSL#24
		STR	R0, [SP,#0x68+var_34]
		MOV	R2, #4
		ADD	R1, SP,	#0x68+var_34
		ADD	R0, R7,	#4
		BL	0x690174

loc_FF0812BC				; CODE XREF: sub_FF080EFC+340j
					; sub_FF080EFC+358j
		LDR	R0, [SP,#0x68+var_24]
		LDR	R1, [SP,#0x68+var_1C]
		BL	sub_FF1EF054
		LDR	R0, [R5,#0x68]
		LDR	R3, =0x3928
		ADD	R1, R0,	#1
		STR	R1, [R5,#0x68]
		LDR	R0, [SP,#0x68+var_1C]
		SUB	R2, R3,	#4
		BL	sub_FF1E9D6C
		LDR	R0, [R5,#0x64]
		CMP	R0, #1
		BNE	loc_FF081340
		ADD	R0, SP,	#0x68+var_38
		BL	sub_FF1963C4
		LDR	R1, =0x4394C
		LDR	R0, [R1,#4]
		LDR	R1, [R1]
		SUB	R2, R0,	#0x400
		SUBS	R2, R2,	#0x38
		ADDEQ	R0, R0,	#8
		MOV	R1, R1,LSR#4
		MOV	R0, R0,LSR#4
		MUL	R1, R0,	R1
		LDR	R0, [SP,#0x68+var_38]
		BL	0x69092C
		LDR	R1, =0x4397C
		STR	R0, [SP,#0x68+var_38]
		BL	sub_FF1EA0A8
		B	loc_FF081340
; ---------------------------------------------------------------------------

loc_FF081334				; CODE XREF: sub_FF080EFC+1F0j
		LDRH	R0, [R5,#6]
		CMP	R0, #3
		BNE	loc_FF0810E0

loc_FF081340				; CODE XREF: sub_FF080EFC+3F0j
					; sub_FF080EFC+434j
		LDR	R0, [R5,#0x6C]
		ADD	R0, R0,	#1
		STR	R0, [R5,#0x6C]
		LDRH	R1, [R5,#6]
		CMP	R1, #3
		LDRNE	R1, [R5,#0x54]
		MULNE	R0, R1,	R0
		LDRNE	R1, [R5,#0x50]
		BNE	loc_FF081380
		LDR	R1, [R5,#0x58]
		CMP	R1, #0x19
		LDRNE	R1, =0x3E9
		MOVEQ	R1, #0x3E8
		MUL	R0, R1,	R0
		LDRNE	R1, =0x1770
		LDREQ	R1, =0x1388

loc_FF081380				; CODE XREF: sub_FF080EFC+464j
		BL	0x69092C
		MOV	R4, R0
		BL	sub_FF1EF714
		LDR	R0, [R5,#0x7C]
		CMP	R0, R4
		BNE	loc_FF0813A4
		LDR	R0, [R5,#0x3C]
		CMP	R0, #1
		BNE	loc_FF0813B8

loc_FF0813A4				; CODE XREF: sub_FF080EFC+498j
		LDR	R1, [R5,#0xA8]
		MOV	R0, R4
		BLX	R1
		STR	R4, [R5,#0x7C]
		STR	R6, [R5,#0x3C]

loc_FF0813B8				; CODE XREF: sub_FF080EFC+4A4j
		STR	R6, [R5,#0x38]
		B	loc_FF0810E0
; End of function sub_FF080EFC

