#include "lolevel.h"
#include "platform.h"
#include "core.h"
static long *nrflag = (long*)0x5BA0;

#include "../../../generic/capt_seq.c"

void __attribute__((naked,noinline)) capt_seq_task() {
 asm volatile (
                 "STMFD   SP!, {R3-R7,LR}\n"
                 "LDR     R6, =0x26DC\n"
 "loc_FFC42F3C:\n"
                 "LDR     R0, [R6,#4]\n"
                 "MOV     R2, #0\n"
                 "MOV     R1, SP\n"
                 "BL      sub_FFC15EBC\n"
                 "TST     R0, #1\n"
                 "BEQ     loc_FFC42F68\n"
                 "LDR     R1, =0x588\n"
                 "LDR     R0, =0xFFC42B3C\n"
                 "BL      sub_FFC0BE9C\n"
                 "BL      sub_FFC0BC54\n"
                 "LDMFD   SP!, {R3-R7,PC}\n"
 "loc_FFC42F68:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0]\n"
                 "CMP     R1, #0x1D\n"
                 "ADDLS   PC, PC, R1,LSL#2\n"
                 "B       loc_FFC43154\n"
 "loc_FFC42F7C:\n"
                 "B       loc_FFC42FF4\n"
 "loc_FFC42F80:\n"
                 "B       loc_FFC42FFC\n"
 "loc_FFC42F84:\n"
                 "B       loc_FFC43024\n"
 "loc_FFC42F88:\n"
                 "B       loc_FFC43038\n"
 "loc_FFC42F8C:\n"
                 "B       loc_FFC43030\n"
 "loc_FFC42F90:\n"
                 "B       loc_FFC43040\n"
 "loc_FFC42F94:\n"
                 "B       loc_FFC43048\n"
 "loc_FFC42F98:\n"
                 "B       loc_FFC43054\n"
 "loc_FFC42F9C:\n"
                 "B       loc_FFC430AC\n"
 "loc_FFC42FA0:\n"
                 "B       loc_FFC43038\n"
 "loc_FFC42FA4:\n"
                 "B       loc_FFC430B4\n"
 "loc_FFC42FA8:\n"
                 "B       loc_FFC430C4\n"
 "loc_FFC42FAC:\n"
                 "B       loc_FFC430CC\n"
 "loc_FFC42FB0:\n"
                 "B       loc_FFC430D4\n"
 "loc_FFC42FB4:\n"
                 "B       loc_FFC430DC\n"
 "loc_FFC42FB8:\n"
                 "B       loc_FFC430E4\n"
 "loc_FFC42FBC:\n"
                 "B       loc_FFC430EC\n"
 "loc_FFC42FC0:\n"
                 "B       loc_FFC430F4\n"
 "loc_FFC42FC4:\n"
                 "B       loc_FFC43100\n"
 "loc_FFC42FC8:\n"
                 "B       loc_FFC43108\n"
 "loc_FFC42FCC:\n"
                 "B       loc_FFC43110\n"
 "loc_FFC42FD0:\n"
                 "B       loc_FFC43118\n"
 "loc_FFC42FD4:\n"
                 "B       loc_FFC43120\n"
 "loc_FFC42FD8:\n"
                 "B       loc_FFC4312C\n"
 "loc_FFC42FDC:\n"
                 "B       loc_FFC43134\n"
 "loc_FFC42FE0:\n"
                 "B       loc_FFC4313C\n"
 "loc_FFC42FE4:\n"
                 "B       loc_FFC43144\n"
 "loc_FFC42FE8:\n"
                 "B       loc_FFC4314C\n"
 "loc_FFC42FEC:\n"
                 "B       loc_FFC43160\n"
 "loc_FFC42FF0:\n"
                 "B       loc_FFC43160\n"
 "loc_FFC42FF4:\n"
                 "BL      sub_FFC437C0\n"
                 "BL      shooting_expo_param_override\n"      // +
                 "B       loc_FFC4304C\n"
 "loc_FFC42FFC:\n"
"     BL    shooting_set_flash_override\n"
                 "MOV     R0, #0xC\n"
                 "BL      sub_FFC46E34\n"
                 "TST     R0, #1\n"
                 "LDR     R0, [SP]\n"
                 "MOVNE   R1, #1\n"
                 "LDRNE   R2, [R0,#0xC]\n"
                 "MOVNE   R0, #1\n"
                 "BNE     loc_FFC430A4\n"
                 "BL      sub_FFC4327C_my\n"  //--------->
                 "B       loc_FFC43160\n"
 "loc_FFC43024:\n"
                 "MOV     R0, #1\n"
                 "BL      sub_FFC4395C\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43030:\n"
                 "BL      sub_FFC43448\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43038:\n"
                 "BL      sub_FFC437A0\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43040:\n"
                 "BL      sub_FFC437A8\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43048:\n"
                 "BL      sub_FFC4387C\n"
 "loc_FFC4304C:\n"
                 "BL      sub_FFC411F8\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43054:\n"
                 "LDR     R4, [R0,#0xC]\n"
                 "BL      sub_FFC437B0\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE88BC\n"
                 "TST     R0, #1\n"
                 "MOV     R5, R0\n"
                 "BNE     loc_FFC43094\n"
                 "BL      sub_FFC51AD4\n"
                 "STR     R0, [R4,#0x18]\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE972C\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE9B80\n"
                 "MOV     R5, R0\n"
                 "LDR     R0, [R4,#0x18]\n"
                 "BL      sub_FFC51CE8\n"
 "loc_FFC43094:\n"
                 "BL      sub_FFC437A0\n"
                 "MOV     R2, R4\n"
                 "MOV     R1, #9\n"
                 "MOV     R0, R5\n"
 "loc_FFC430A4:\n"
                 "BL      sub_FFC41628\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430AC:\n"
                 "BL      sub_FFC438DC\n"
                 "B       loc_FFC4304C\n"
 "loc_FFC430B4:\n"
                 "LDR     R0, =0x12A48\n"
                 "LDR     R0, [R0,#0x4C]\n"
                 "BL      sub_FFC43C70\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430C4:\n"
                 "BL      sub_FFC43F18\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430CC:\n"
                 "BL      sub_FFC43FAC\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430D4:\n"
                 "BL      sub_FFCE8AD8\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430DC:\n"
                 "BL      sub_FFCE8CC0\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430E4:\n"
                 "BL      sub_FFCE8D50\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430EC:\n"
                 "BL      sub_FFCE8DF8\n"
                 "B       loc_FFC43160\n"
 "loc_FFC430F4:\n"
                 "MOV     R0, #0\n"
                 "BL      sub_FFCE8FB4\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43100:\n"
                 "BL      sub_FFCE90F4\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43108:\n"
                 "BL      sub_FFCE9188\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43110:\n"
                 "BL      sub_FFCE924C\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43118:\n"
                 "BL      sub_FFC43AC4\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43120:\n"
                 "BL      sub_FFC43AF0\n"
                 "BL      sub_FFC13F74\n"
                 "B       loc_FFC43160\n"
 "loc_FFC4312C:\n"
                 "BL      sub_FFCE8EB4\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43134:\n"
                 "BL      sub_FFCE8EF8\n"
                 "B       loc_FFC43160\n"
 "loc_FFC4313C:\n"
                 "BL      sub_FFC45A70\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43144:\n"
                 "BL      sub_FFC45A8C\n"
                 "B       loc_FFC43160\n"
 "loc_FFC4314C:\n"
                 "BL      sub_FFC45A9C\n"
                 "B       loc_FFC43160\n"
 "loc_FFC43154:\n"
                 "LDR     R1, =0x6C9\n"
                 "LDR     R0, =0xFFC42B3C\n"
                 "BL      sub_FFC0BE9C\n"
 "loc_FFC43160:\n"
                 "LDR     R0, [SP]\n"
                 "LDR     R1, [R0,#4]\n"
                 "LDR     R0, [R6]\n"
                 "BL      sub_FFC15C2C\n"
                 "LDR     R4, [SP]\n"
                 "LDR     R0, [R4,#8]\n"
                 "CMP     R0, #0\n"
                 "LDREQ   R1, =0x12B\n"
                 "LDREQ   R0, =0xFFC42B3C\n"
                 "BLEQ    sub_FFC0BE9C\n"
                 "MOV     R0, #0\n"
                 "STR     R0, [R4,#8]\n"
                 "B       loc_FFC42F3C\n"
 );
} 



void __attribute__((naked,noinline)) sub_FFC4327C_my(){ // 
 asm volatile(
                 "STMFD   SP!, {R3-R5,LR}\n"
                 "LDR     R4, [R0,#0xC]\n"
                 "LDR     R0, [R4,#8]\n"
                 "ORR     R0, R0, #1\n"
                 "STR     R0, [R4,#8]\n"
                 "BL      sub_FFC437B0\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFC43A78\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE854C\n"
                 "CMP     R0, #0\n"
                 "MOV     R0, R4\n"
                 "BEQ     loc_FFC432CC\n"
                 "BL      sub_FFCE85E8\n"
                 "TST     R0, #1\n"
                 "MOVNE   R2, R4\n"
                 "LDMNEFD SP!, {R3-R5,LR}\n"
                 "MOVNE   R1, #1\n"
                 "BNE     sub_FFC41628\n"
                 "B       loc_FFC432D0\n"
 "loc_FFC432CC:\n"
                 "BL      sub_FFCE859C\n"
 "loc_FFC432D0:\n"
                 "MOV     R0, #0\n"
                 "STR     R0, [SP]\n"
                 "LDR     R0, =0x12A48\n"
                 "MOV     R2, #2\n"
                 "LDRH    R0, [R0,#0x8E]\n"
                 "MOV     R1, SP\n"
                 "CMP     R0, #3\n"
                 "LDRNE   R0, [R4,#0xC]\n"
                 "CMPNE   R0, #1\n"
                 "MOVHI   R0, #1\n"
                 "STRHI   R0, [SP]\n"
                 "LDR     R0, =0x123\n"
                 "BL      sub_FFC5183C\n"
                 "BL      sub_FFC51AD4\n"
                 "STR     R0, [R4,#0x18]\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE972C\n"
                 "BL      sub_FFCEA1F4\n"
                 "MOV     R0, R4\n"
                 "BL      sub_FFCE97F4_my\n"             //---------->
                 "MOV     R5, R0\n"
                 "BL      capt_seq_hook_raw_here\n"      // +
                 "BL      sub_FFC45A8C\n"
                 "BL      sub_FFC45AC8\n"
                 "MOV     R2, R4\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, R5\n"
                 "BL      sub_FFC41628\n"
                 "BL      sub_FFCE9B24\n"
                 "CMP     R0, #0\n"
                 "LDRNE   R0, [R4,#8]\n"
                 "ORRNE   R0, R0, #0x2000\n"
                 "STRNE   R0, [R4,#8]\n"
                 "LDMFD   SP!, {R3-R5,PC}\n"
 );
}



void __attribute__((naked,noinline)) sub_FFCE97F4_my(){ // 
 asm volatile(
                 "STMFD   SP!, {R0-R8,LR}\n"
                 "MOV     R4, R0\n"
                 "BL      sub_FFCEA360\n"
                 "MVN     R1, #0\n"
                 "BL      sub_FFC15C60\n"
                 "LDR     R5, =0x5BA0\n"
                 "LDR     R0, [R5,#0xC]\n"
                 "CMP     R0, #0\n"
                 "BNE     loc_FFCE9844\n"
                 "MOV     R1, #1\n"
                 "MOV     R0, #0\n"
                 "BL      sub_FFC0BCD0\n"
                 "STR     R0, [R5,#0xC]\n"
                 "MOV     R3, #0\n"
                 "STR     R3, [SP]\n"
                 "LDR     R3, =0xFFCE9340\n"
                 "LDR     R0, =0xFFCE9AEC\n"
                 "MOV     R2, #0x400\n"
                 "MOV     R1, #0x17\n"
                 "BL      sub_FFC0BC9C\n"
 "loc_FFCE9844:\n"
                 "MOV     R2, #4\n"
                 "ADD     R1, SP, #8\n"
                 "MOV     R0, #0x8A\n"
                 "BL      sub_FFC51944\n"
                 "TST     R0, #1\n"
                 "LDRNE   R1, =0x3A7\n"
                 "LDRNE   R0, =0xFFCE956C\n"
                 "BLNE    sub_FFC0BE9C\n"
                 "LDR     R8, =0x12B04\n"
                 "LDR     R7, =0x12A48\n"
                 "LDRSH   R1, [R8,#0xE]\n"
                 "LDR     R0, [R7,#0x84]\n"
            //   "BL      nullsub_27\n"
                 "BL      sub_FFC2E8F0\n"
                 "LDR     R3, =0x5BA8\n"
                 "STRH    R0, [R4,#0x9C]\n"
                 "SUB     R2, R3, #4\n"
                 "STRD    R2, [SP]\n"
                 "MOV     R1, R0\n"
                 "LDRH    R0, [R7,#0x54]\n"
                 "LDRSH   R2, [R8,#0xC]\n"
                 "SUB     R3, R3, #8\n"
                 "BL      sub_FFCEA944\n"                            
                 "BL      wait_until_remote_button_is_released\n"     // +
                 "BL      capt_seq_hook_set_nr\n"                     // +
                 "B       sub_FFCE98A0\n"                             // continue function in firmware
 );
}

